version: '3.7'

services:

  database-server:
    image: 'mongo'
    container_name: 'finance-database'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=finance-database-root
      - MONGO_INITDB_ROOT_PASSWORD=finance-database-root      
    ports:
      - 27017:27017
    volumes:
      - ./mongo/scripts:/docker-entrypoint-initdb.d
    networks:
      - finance-network

    # https://lists.jboss.org/pipermail/keycloak-user/2018-June/014337.html
  identity-server:
    image: 'jboss/keycloak'
    container_name: 'finance-identity'
    environment: 
      - KEYCLOAK_USER=finance-identity-root
      - KEYCLOAK_PASSWORD=finance-identity-root
      - KEYCLOAK_IMPORT=/tmp/realm.json
      - KEYCLOAK_HTTP_PORT=9080
      - PROXY_ADDRESS_FORWARDING=true      
    ports:
      - 9080:9080
    volumes:      
      - ./keycloak/realm.json:/tmp/realm.json      
    networks:
      - finance-network
  
  backend-server:
    image: 'maven'
    container_name: 'finance-backend'
    ports:
      - 8080:8080
    volumes:
      - ../../backend:/usr/src/finance
      - C:/dev-tools/apache-maven-3.6.2/conf/settings.xml:/usr/share/maven/ref/settings.xml
    networks:
      - finance-network
    working_dir: /usr/src/finance
    depends_on:
      - database-server
      - identity-server
    command: >
      bash -c "export HTTP_PROXY=http://proxy.corp.panalpina.com:10139
      && export HTTPS_PROXY=http://proxy.corp.panalpina.com:10139
      && mvn spring-boot:run -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true"

  backend-proxy-server:
      image: nginx      
      container_name: finance-backend-proxy
      ports:
        - 81:81
      volumes:      
        - ./nginx-backend/nginx-finance-backend.conf:/etc/nginx/conf.d/nginx-finance-backend.conf
        #  - ./nginx-backend/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - backend-server
      networks:
        - finance-network
      command: ['nginx-debug', '-g', 'daemon off;']

  frontend-server:
      image: 'node'
      container_name: finance-frontend
      working_dir: /home/node/app
      volumes:
        - ../../frontend/:/home/node/app/
      ports:
        - 4200:4200
      networks:
        - finance-network
      depends_on:
       - backend-proxy-server
      command: >
        bash -c "export HTTP_PROXY=http://proxy.corp.panalpina.com:10139
        && export HTTPS_PROXY=http://proxy.corp.panalpina.com:10139
        && npm config set proxy http://proxy.corp.panalpina.com:10139
        && npm config set https-proxy http://proxy.corp.panalpina.com:10139
        && npm config set strict-ssl false
        && echo n | npm install -g @angular/cli@8.0.1
        && npm install
        && ng serve --host 0.0.0.0"
  
networks:
  finance-network: