version: '3.7'

services:

  # mongodb://finance-user:finance-user@database.finance.com.br:80/finance
  database-server:
    image: 'mongo'
    container_name: 'finance-database'
    extra_hosts:
      - "host.docker.internal:$DOCKER_HOST_IP"    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=finance-database-root
      - MONGO_INITDB_ROOT_PASSWORD=finance-database-root      
    ports:
      - 27017:27017
    volumes:
      - ./mongo/scripts:/docker-entrypoint-initdb.d
    networks:
      - finance-network

    # https://lists.jboss.org/pipermail/keycloak-user/2018-June/014337.html

    #http://172.23.0.3:8080/auth/realms/finance/.well-known/openid-configuration
    #http://identity.finance.com.br/auth/realms/finance/.well-known/openid-configuration
  identity-server:
    image: 'jboss/keycloak'
    container_name: 'finance-identity'
    extra_hosts:
      - "host.docker.internal:$DOCKER_HOST_IP"    
    environment: 
      - KEYCLOAK_USER=finance-identity-root
      - KEYCLOAK_PASSWORD=finance-identity-root
      - KEYCLOAK_IMPORT=/tmp/realm.json
      - PROXY_ADDRESS_FORWARDING=true      
    ports:
      - 9080:8080
    volumes:      
      - ./keycloak/realm.json:/tmp/realm.json      
    networks:
      - finance-network
  
  backend-server:
    image: 'maven'
    container_name: 'finance-backend'
    extra_hosts:
      - "host.docker.internal:$DOCKER_HOST_IP"
      - "identity.finance.com.br:$HOST_IP"    
    ports:
      - 8080:8080
    volumes:
      - ../../backend:/usr/src/finance
    networks:
      - finance-network
    working_dir: /usr/src/finance
    depends_on:
      - database-server
      - identity-server
    command: >
      bash -c "mvn spring-boot:run -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true"

  proxy-server:
      image: nginx
      container_name: finance-proxy
      extra_hosts:
        - "host.docker.internal:$DOCKER_HOST_IP"      
      ports:
        - 80:80
      volumes:        
        - ./nginx-backend/:/etc/nginx/:ro
      depends_on:
        - backend-server
      networks:
        - finance-network
      command: ['nginx-debug', '-g', 'daemon off;']

  frontend-server:
      image: 'node'
      container_name: finance-frontend
      extra_hosts:
        - "host.docker.internal:$DOCKER_HOST_IP"          
      working_dir: /home/node/app
      volumes:
        - ../../frontend/:/home/node/app/
      ports:
        - 4200:4200
      networks:
        - finance-network
      depends_on:
       - proxy-server
      command: >
        bash -c "npm config set strict-ssl false
        && echo n | npm install -g @angular/cli@8.0.1
        && npm install
        && ng serve --host 0.0.0.0"
  
networks:
  finance-network: