spring:
   data:
      mongodb:
         host: finance-database
         port: 27017
         database: finance
         username: finance-user
         password: finance-user

   jackson:
      default-property-inclusion: NON_NULL 

logging:
   level:
      org.springframework.data.mongodb.core.MongoTemplate: INFO
      org.springframework.security: DEBUG
      com.finance: DEBUG

keycloak:
   realm: finance
   auth-server-url: http://identity.finance.com.br/auth
   ssl-required: external
   resource: finance-manager
   credentials:
      secret: 78f59ce6-ae53-44a7-9ac8-36482164b7e8
   use-resource-role-mappings :  true
   bearer-only: true
   principal-attribute: preferred_username