spring:
   data:
      mongodb:
         host: finance-database
         port: 27017
         database: finance
         username: finance-user
         password: finance-user

   jackson:
      default-property-inclusion: NON_NULL 

logging:
   level:
      org.springframework.data.mongodb.core.MongoTemplate: INFO
      org.springframework.security: DEBUG
      com.finance: DEBUG

keycloak:
   realm: finance
   auth-server-url: http://finance-backend-proxy:81/auth
   ssl-required: external
   resource: finance-manager
   credentials:
      secret: 552795b4-ea24-409b-a18f-3afe12abeb47
   use-resource-role-mappings :  true
   bearer-only: true
   principal-attribute: preferred_username