spring:
   data:
      mongodb:
         host: finance-database
         port: 27017
         database: finance
         username: finance-user
         password: finance-user

   jackson:
      default-property-inclusion: NON_NULL

logging:
   level:
      org.springframework.data.mongodb.core.MongoTemplate: INFO
      org.springframework.security: DEBUG
      com.finance: DEBUG

keycloak:
   realm: finance
   auth-server-url: http://identity.finance.com.br:8080/auth
   ssl-required: external
   resource: finance-manager
   credentials:
      secret: 685aa0fa-c830-465d-95ff-895c1830760a
   use-resource-role-mappings :  true
   bearer-only: true
   principal-attribute: preferred_username