spring:
   data:
      mongodb:
         host: 127.0.0.1
         port: 27017
         database: finance
         username: finance-user
         password: finance-user

   jackson:
      default-property-inclusion: NON_NULL

logging:
   level:
      #org.springframework.data.mongodb.core.MongoTemplate: DEBUG
      org.springframework.security: DEBUG
      #org.springframework: DEBUG
      com.finance: DEBUG

keycloak:
   realm: finance
   auth-server-url: http://localhost:8180/auth
   ssl-required: external
   resource: finance-manager
   credentials:
      secret: 30d2f5b8-d228-491e-8376-e0728bb55043
   use-resource-role-mappings :  true
   bearer-only: true
   principal-attribute: preferred_username